### ISSUE TITLE
Do you have single image SR support?

### ISSUE THREAD

**Issue by roimulia2** [YingqianWang/LF-DAnet#2]
Hey, loved the paper! 

Seems like you have an examples of .mp4 SR. Can I run it on an image? Also, what is the recommended input image resolution, and what is the output?

Thanks!

**Comment by YingqianWang** [comment]
Hello, thanks for your attention to our work! 

1. Our LF-DAnet is proposed to handle the light field (LF) image super-resolution task, in which an AxA array of images (record the same scene but with disparities) are simultaneously super-resolved. You can refer to [DistgSSR](https://yingqianwang.github.io/DistgLF/) (TPAMI 2022) to learn more about this task.  
2. Our LF-DAnet can be also used to super-resolve single images. To achieve that, you can copy and paste the input single image to generate an AxA pseudo image array with identical contents, and then feed this image array to our network. Then, our network will produce the HR version of this pseudo image array.
3. Our method can be used to super-resolve input LF images of arbitrary resolution. However, according to our observations, our LF-DAnet performs better on real-world images captured by Lytro cameras (with a resolution of 600x400).

**Comment by roimulia2** [comment]
Thank you so much for the detailed responses - got it!
